FROM python:3.10-slim

WORKDIR /microservicios

COPY db_service.py .

RUN pip install fastapi uvicorn pydantic requests mysql-connector-python

CMD ["uvicorn", "db_service:app", "--host", "0.0.0.0", "--port", "8000"]