# Usar una imagen ligera de Python
FROM python:3.9-alpine

# Definir el directorio de trabajo
WORKDIR /app

# Copiar archivos del proyecto al contenedor
COPY . .

# Ejecutar el script al iniciar el contenedor
CMD ["python", "simulador.py"]
