--liquibase formatted sql

--changeset santosa:002-add-users-table
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL,
    email VARCHAR2(255) NOT NULL
);