--liquibase formatted sql
--changeset santosa:003-create-students-table

-- Create students table with all required fields and constraints
CREATE TABLE students (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(255) NOT NULL,
    enrollment_date DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Add unique constraint for email
ALTER TABLE students ADD CONSTRAINT uk_students_email UNIQUE (email);

-- Create index on email for better performance
CREATE INDEX idx_students_email ON students(email);

-- Create index on enrollment_date for queries
CREATE INDEX idx_students_enrollment_date ON students(enrollment_date);

-- Add comments to document the table
COMMENT ON TABLE students IS 'Student information table for academic management';
COMMENT ON COLUMN students.id IS 'Primary key - auto-incrementing student ID';
COMMENT ON COLUMN students.first_name IS 'Student first name';
COMMENT ON COLUMN students.last_name IS 'Student last name';
COMMENT ON COLUMN students.email IS 'Student email address - must be unique';
COMMENT ON COLUMN students.enrollment_date IS 'Date when student enrolled';
COMMENT ON COLUMN students.created_at IS 'Record creation timestamp';