# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'User_Add_View.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import images.images

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(701, 498)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, -110, 801, 741))
        self.label.setStyleSheet("image: url(:/images1/one_Piece.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 321, 71))
        self.label_2.setStyleSheet("font: 87 16pt \"Arial Black\";")
        self.label_2.setObjectName("label_2")
        self.btnAddNakama = QtWidgets.QPushButton(Dialog)
        self.btnAddNakama.setGeometry(QtCore.QRect(80, 320, 131, 51))
        self.btnAddNakama.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"color: white;\n"
"font: 87 8pt \"Arial Black\";")
        self.btnAddNakama.setObjectName("btnAddNakama")
        self.le_Name = QtWidgets.QLineEdit(Dialog)
        self.le_Name.setGeometry(QtCore.QRect(50, 140, 201, 41))
        self.le_Name.setObjectName("le_Name")
        self.le_Rol = QtWidgets.QLineEdit(Dialog)
        self.le_Rol.setGeometry(QtCore.QRect(50, 200, 201, 41))
        self.le_Rol.setObjectName("le_Rol")
        self.le_Crew = QtWidgets.QLineEdit(Dialog)
        self.le_Crew.setGeometry(QtCore.QRect(50, 260, 201, 41))
        self.le_Crew.setObjectName("le_Crew")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(0, 470, 711, 31))
        self.label_5.setStyleSheet("font: 87 18pt \"Arial Black\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.125, x2:0.334, y2:1, stop:0.0895522 rgba(146, 169, 190, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 711, 51))
        self.label_6.setStyleSheet("font: 87 18pt \"Arial Black\";\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0.556818, x2:0, y2:0.42, stop:0 rgba(157, 197, 235, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(109, 112, 116);")
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(540, 460, 231, 41))
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(620, -10, 111, 61))
        self.label_7.setStyleSheet("image: url(:/images1/lufy.png);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Nakama Information"))
        self.btnAddNakama.setText(_translate("Dialog", "Insert new user"))
        self.le_Name.setPlaceholderText(_translate("Dialog", "Name"))
        self.le_Rol.setPlaceholderText(_translate("Dialog", "Rol"))
        self.le_Crew.setPlaceholderText(_translate("Dialog", "Crew"))
        self.label_6.setText(_translate("Dialog", " System to add new Nakamas "))
        self.label_4.setText(_translate("Dialog", "Welcome to the team :D"))
